### ISSUE TITLE
Setting up git on a new computer

### ISSUE THREAD

**Issue by iteles** [dwyl/dev-setup#44]
The URL that our `readme` currently takes you to to set up SSH (https://docs.github.com/en/get-started/quickstart/set-up-git#connecting-over-ssh) is a bit useless as it just redirects you to a path which requires 4 more clicks to get to the one you actually want: https://docs.github.com/en/authentication/connecting-to-github-with-ssh

## Tasks
+ [ ] Set up git on my computer and take screenshots
+ [ ] Update https://github.com/dwyl/dev-setup#basic-git-setup to be clearer in terms of what needs to be done
+ [ ] Refer to the correct links as mentioned above - no need to reinvent the wheel

**Comment by iteles** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4185328/168640404-3fb421aa-009a-400d-b917-c32c1e65ec95.png">
